server:
  port: 8100
  servlet:
    context-path: /api

spring:
  application:
    name : courier-tracking
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/courierdb
    username: courier
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

store:
  entry:
    radius: 100 # in meters

logging:
  level:
    org.zalando.logbook: TRACE
    com.migros: DEBUG